/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by countries
select 
     country,
     count(customer_key) as total_customers
from gold.dim_customers
group by country
order by total_customers desc

-- Find total customers by gender
select
    gender,
    count(customer_key) as total_customers
from gold.dim_customers
group by gender
order by total_customers desc

-- Find total products by category
select 
    category,
    count(product_key) as total_products
from gold.dim_products
group by category
order by total_products desc

-- What is the average costs in each category?
select 
    category,
    avg(cost) as cost
from gold.dim_products
group by category
order by cost desc

-- What is the total revenue generated for each category?
select 
    gdp.category,
    sum(gfs.sales_amount) as total_revenue
from gold.fact_sales gfs
left join gold.dim_products gdp
on gfs.product_key = gdp.product_key
group by category
order by total_revenue desc

-- What is the total revenue generated by each customer?
select
    dc.customer_key,
    dc.first_name,
    dc.last_name,
    sum(sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_customers dc
on f.customer_key = dc.customer_key
group by dc.customer_key, dc.first_name, dc.last_name
order by total_revenue desc

-- What is the distribution of sold items across countries?
select
    dc.country,
    sum(f.quantity) as sold_items
from gold.fact_sales f
left join gold.dim_customers dc
on f.customer_key = dc.customer_key
group by dc.country
order by sold_items desc
